name: glance
version: ocata
summary: OpenStack Image Service (glance)
description: |
  Glance is a project that provides services and associated libraries
  to store, browse, share, distribute and manage bootable disk images,
  other data closely associated with initializing compute resources,
  and metadata definitions.
confinement: classic
grade: devel

environment:
  PATH: $PATH:$SNAP/bin/

apps:
  api:
    command: snap-openstack glance-api
    daemon: simple
  registry:
    command: snap-openstack glance-registry
    daemon: simple
  manage:
    command: snap-openstack glance-manage
    aliases:
      - glance-manage

parts:
  glance:
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/glance/glance-master.tar.gz
    python-packages:
      - pymysql
      - httplib2
      - python-swiftclient
      - os-brick
      - python-cinderclient
      - oslo.rootwrap
      - oslo.vmware
      - python-memcached
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/master/upper-constraints.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
  templates:
    after: [glance]
    plugin: dump
    source: snap
  # TODO: replace below with scriplets once implemented in snapcraft
  config:
    after: [glance]
    plugin: dump
    source: http://tarballs.openstack.org/glance/glance-master.tar.gz
    organize:
      etc/*.conf: etc/glance/
      etc/*.ini: etc/glance/
      etc/*.json: etc/glance/
    filesets:
      etc:
        - etc/glance/*.conf
        - etc/glance/*.ini
        - etc/glance/*.json
    stage: [$etc]
    snap: [$etc]
